#!/usr/bin/make
# Automatically generated by KiBot from `ngff.kibot.yaml`
KIBOT=kibot
DEBUG=
CONFIG=ngff.kibot.yaml
SCH=ngff.sch
PCB=ngff.kicad_pcb
DEST=Fabrication
KIBOT_CMD=$(KIBOT) $(DEBUG) -c $(CONFIG) -e $(SCH) -b $(PCB) -d $(DEST)
LOGFILE=kibot_error.log

#
# Default target
#
all: run_erc run_drc Elecrow_gerbers Elecrow_drill Elecrow FusionPCB_gerbers FusionPCB_drill FusionPCB JLCPCB_gerbers JLCPCB_drill JLCPCB P-Ban_gerbers P-Ban_drill P-Ban PCBWay_gerbers PCBWay_drill PCBWay print_sch print_front print_bottom print_gnd print_power print_s1 print_s2 interactive_bom bom_html bom_xlsx bom_csv gerbers excellon_drill gerber_drills position pcb_top_g pcb_bot_g pcb_top_b pcb_bot_b pcb_top_r pcb_bot_r step

#
# SCH/PCB targets
#
pre_sch: run_erc

out_sch: print_sch bom_html bom_xlsx bom_csv

all_sch: pre_sch out_sch

pre_pcb: run_drc

out_pcb: Elecrow_gerbers Elecrow_drill Elecrow FusionPCB_gerbers FusionPCB_drill FusionPCB JLCPCB_gerbers JLCPCB_drill JLCPCB P-Ban_gerbers P-Ban_drill P-Ban PCBWay_gerbers PCBWay_drill PCBWay print_front print_bottom print_gnd print_power print_s1 print_s2 interactive_bom gerbers excellon_drill gerber_drills position pcb_top_g pcb_bot_g pcb_top_b pcb_bot_b pcb_top_r pcb_bot_r step

all_pcb: pre_pcb out_pcb

#
# Available targets (outputs)
#
run_erc: Fabrication/template-erc_0.1.txt

run_drc: Fabrication/template-drc_0.1.txt

Elecrow_gerbers: Fabrication/Elecrow/ngff.GTL Fabrication/Elecrow/ngff.G1 Fabrication/Elecrow/ngff.G2 Fabrication/Elecrow/ngff.G3 Fabrication/Elecrow/ngff.G4 Fabrication/Elecrow/ngff.GBL Fabrication/Elecrow/ngff.GTO Fabrication/Elecrow/ngff.GBO Fabrication/Elecrow/ngff.GTS Fabrication/Elecrow/ngff.GBS Fabrication/Elecrow/ngff.GML

Elecrow_drill: Fabrication/Elecrow/ngff.TXT Fabrication/Elecrow/template-NPTH.TXT

Elecrow: Fabrication/Elecrow/template-Elecrow_0.1.zip

FusionPCB_gerbers: Fabrication/FusionPCB/ngff.GTL Fabrication/FusionPCB/ngff.GL2 Fabrication/FusionPCB/ngff.GL3 Fabrication/FusionPCB/ngff.GL4 Fabrication/FusionPCB/ngff.GL5 Fabrication/FusionPCB/ngff.GBL Fabrication/FusionPCB/ngff.GTO Fabrication/FusionPCB/ngff.GBO Fabrication/FusionPCB/ngff.GTS Fabrication/FusionPCB/ngff.GBS Fabrication/FusionPCB/ngff.GML

FusionPCB_drill: Fabrication/FusionPCB/ngff.TXT

FusionPCB: Fabrication/FusionPCB/template-FusionPCB_0.1.zip

JLCPCB_gerbers: Fabrication/JLCPCB/template-F_Cu_0.1.gbr Fabrication/JLCPCB/template-B_Cu_0.1.gbr Fabrication/JLCPCB/template-In1_Cu_0.1.gbr Fabrication/JLCPCB/template-In2_Cu_0.1.gbr Fabrication/JLCPCB/template-In3_Cu_0.1.gbr Fabrication/JLCPCB/template-In4_Cu_0.1.gbr Fabrication/JLCPCB/template-F_SilkS_0.1.gbr Fabrication/JLCPCB/template-B_SilkS_0.1.gbr Fabrication/JLCPCB/template-F_Mask_0.1.gbr Fabrication/JLCPCB/template-B_Mask_0.1.gbr Fabrication/JLCPCB/template-Edge_Cuts_0.1.gbr

JLCPCB_drill: Fabrication/JLCPCB/template-PTH.drl Fabrication/JLCPCB/template-NPTH.drl

JLCPCB: Fabrication/JLCPCB/template-JLCPCB_0.1.zip

P-Ban_gerbers: Fabrication/P-Ban/template-F_Cu_0.1.gtl Fabrication/P-Ban/template-B_Cu_0.1.gbl Fabrication/P-Ban/template-In1_Cu_0.1.gp1 Fabrication/P-Ban/template-In2_Cu_0.1.gp2 Fabrication/P-Ban/template-In3_Cu_0.1.gp3 Fabrication/P-Ban/template-In4_Cu_0.1.gp4 Fabrication/P-Ban/template-F_SilkS_0.1.gto Fabrication/P-Ban/template-B_SilkS_0.1.gbo Fabrication/P-Ban/template-F_Mask_0.1.gts Fabrication/P-Ban/template-B_Mask_0.1.gbs Fabrication/P-Ban/template-Edge_Cuts_0.1.gm1 Fabrication/P-Ban/製造基準書.txt

P-Ban_drill: Fabrication/P-Ban/ngff.drl Fabrication/P-Ban/template-drill_map_0.1.gbr Fabrication/P-Ban/template-drl.rpt

P-Ban: Fabrication/P-Ban/template-P-Ban_0.1.zip

PCBWay_gerbers: Fabrication/PCBWay/ngff.gtl Fabrication/PCBWay/ngff.gl2 Fabrication/PCBWay/ngff.gl3 Fabrication/PCBWay/ngff.gl4 Fabrication/PCBWay/ngff.gl5 Fabrication/PCBWay/ngff.gbl Fabrication/PCBWay/ngff.gto Fabrication/PCBWay/ngff.gbo Fabrication/PCBWay/ngff.gts Fabrication/PCBWay/ngff.gbs Fabrication/PCBWay/ngff.gtp Fabrication/PCBWay/ngff.gbp Fabrication/PCBWay/ngff.gm1

PCBWay_drill: Fabrication/PCBWay/ngff.drl Fabrication/PCBWay/template-NPTH.drl

PCBWay: Fabrication/PCBWay/template-PCBWay_0.1.zip

print_sch: Fabrication/template-schematic_0.1.pdf

print_front: Fabrication/template-F_Cu+Dwgs_User_0.1.pdf

print_bottom: Fabrication/template-B_Cu+Dwgs_User_0.1.pdf

print_gnd: Fabrication/template-GND+Dwgs_User_0.1.pdf

print_power: Fabrication/template-Power_+3,3V+Dwgs_User_0.1.pdf

print_s1: Fabrication/template-S1_Cu+Dwgs_User_0.1.pdf

print_s2: Fabrication/template-S2_Cu+Dwgs_User_0.1.pdf

interactive_bom: Fabrication/BoM/template-ibom_0.1.html

bom_html: Fabrication/BoM/template-bom_0.1.html

bom_xlsx: Fabrication/BoM/template-bom_0.1.xlsx

bom_csv: Fabrication/BoM/template-bom_0.1.csv

gerbers: Fabrication/Gerbers/template-F_Cu_0.1.gbr Fabrication/Gerbers/template-B_Cu_0.1.gbr Fabrication/Gerbers/template-GND_Cu_0.1.gbr Fabrication/Gerbers/template-Power_Cu_0.1.gbr Fabrication/Gerbers/template-S1_Cu_0.1.gbr Fabrication/Gerbers/template-S2_Cu_0.1.gbr Fabrication/Gerbers/template-F_Paste_0.1.gbr Fabrication/Gerbers/template-B_Paste_0.1.gbr Fabrication/Gerbers/template-F_SilkS_0.1.gbr Fabrication/Gerbers/template-B_SilkS_0.1.gbr Fabrication/Gerbers/template-F_Mask_0.1.gbr Fabrication/Gerbers/template-B_Mask_0.1.gbr Fabrication/Gerbers/template-Dwgs_User_0.1.gbr Fabrication/Gerbers/template-Edge_Cuts_0.1.gbr Fabrication/Gerbers/template-B_Fab_0.1.gbr Fabrication/Gerbers/template-job.gbrjob

excellon_drill: Fabrication/Drill/template-PTH_drill_0.1.drl Fabrication/Drill/template-PTH_drill_map_0.1.pdf Fabrication/Drill/template-NPTH_drill_0.1.drl Fabrication/Drill/template-NPTH_drill_map_0.1.pdf Fabrication/Drill/template-drl.rpt

gerber_drills: Fabrication/Drill/template-PTH_drill_0.1.gbr Fabrication/Drill/template-NPTH_drill_0.1.gbr

position: Fabrication/Position/template-top_pos_0.1.pos Fabrication/Position/template-bottom_pos_0.1.pos

pcb_top_g: Fabrication/PCB/green/template-top_0.1.jpg

pcb_bot_g: Fabrication/PCB/green/template-bottom_0.1.jpg

pcb_top_b: Fabrication/PCB/blue/template-top_0.1.jpg

pcb_bot_b: Fabrication/PCB/blue/template-bottom_0.1.jpg

pcb_top_r: Fabrication/PCB/red/template-top_0.1.jpg

pcb_bot_r: Fabrication/PCB/red/template-bottom_0.1.jpg

step: Fabrication/3D/template-3D_0.1.step

#
# Rules and dependencies
#
Fabrication/template-erc_0.1.txt: Power.sch ngff.sch ngff.kibot.yaml
	@$(KIBOT_CMD) -s run_drc -i 2>> $(LOGFILE)

Fabrication/template-drc_0.1.txt: ngff.kicad_pcb ngff.kibot.yaml
	@$(KIBOT_CMD) -s run_erc -i 2>> $(LOGFILE)

# Gerbers compatible with Elecrow
Fabrication/Elecrow/ngff.GTL Fabrication/Elecrow/ngff.G1 Fabrication/Elecrow/ngff.G2 Fabrication/Elecrow/ngff.G3 Fabrication/Elecrow/ngff.G4 Fabrication/Elecrow/ngff.GBL Fabrication/Elecrow/ngff.GTO Fabrication/Elecrow/ngff.GBO Fabrication/Elecrow/ngff.GTS Fabrication/Elecrow/ngff.GBS Fabrication/Elecrow/ngff.GML: ngff.kicad_pcb ngff.kibot.yaml
	@$(KIBOT_CMD) -s all Elecrow_gerbers 2>> $(LOGFILE)

# Drill files compatible with Elecrow
Fabrication/Elecrow/ngff.TXT Fabrication/Elecrow/template-NPTH.TXT: ngff.kicad_pcb ngff.kibot.yaml
	@$(KIBOT_CMD) -s all Elecrow_drill 2>> $(LOGFILE)

# ZIP file for Elecrow
Fabrication/Elecrow/template-Elecrow_0.1.zip: ngff.kibot.yaml
	@$(KIBOT_CMD) -s all Elecrow 2>> $(LOGFILE)

# Gerbers compatible with FusionPCB
Fabrication/FusionPCB/ngff.GTL Fabrication/FusionPCB/ngff.GL2 Fabrication/FusionPCB/ngff.GL3 Fabrication/FusionPCB/ngff.GL4 Fabrication/FusionPCB/ngff.GL5 Fabrication/FusionPCB/ngff.GBL Fabrication/FusionPCB/ngff.GTO Fabrication/FusionPCB/ngff.GBO Fabrication/FusionPCB/ngff.GTS Fabrication/FusionPCB/ngff.GBS Fabrication/FusionPCB/ngff.GML: ngff.kicad_pcb ngff.kibot.yaml
	@$(KIBOT_CMD) -s all FusionPCB_gerbers 2>> $(LOGFILE)

# Drill files compatible with FusionPCB
Fabrication/FusionPCB/ngff.TXT: ngff.kicad_pcb ngff.kibot.yaml
	@$(KIBOT_CMD) -s all FusionPCB_drill 2>> $(LOGFILE)

# ZIP file for FusionPCB
Fabrication/FusionPCB/template-FusionPCB_0.1.zip: ngff.kibot.yaml
	@$(KIBOT_CMD) -s all FusionPCB 2>> $(LOGFILE)

# Gerbers compatible with JLCPCB
Fabrication/JLCPCB/template-F_Cu_0.1.gbr Fabrication/JLCPCB/template-B_Cu_0.1.gbr Fabrication/JLCPCB/template-In1_Cu_0.1.gbr Fabrication/JLCPCB/template-In2_Cu_0.1.gbr Fabrication/JLCPCB/template-In3_Cu_0.1.gbr Fabrication/JLCPCB/template-In4_Cu_0.1.gbr Fabrication/JLCPCB/template-F_SilkS_0.1.gbr Fabrication/JLCPCB/template-B_SilkS_0.1.gbr Fabrication/JLCPCB/template-F_Mask_0.1.gbr Fabrication/JLCPCB/template-B_Mask_0.1.gbr Fabrication/JLCPCB/template-Edge_Cuts_0.1.gbr: ngff.kicad_pcb ngff.kibot.yaml
	@$(KIBOT_CMD) -s all JLCPCB_gerbers 2>> $(LOGFILE)

# Drill files compatible with JLCPCB
Fabrication/JLCPCB/template-PTH.drl Fabrication/JLCPCB/template-NPTH.drl: ngff.kicad_pcb ngff.kibot.yaml
	@$(KIBOT_CMD) -s all JLCPCB_drill 2>> $(LOGFILE)

# ZIP file for JLCPCB
Fabrication/JLCPCB/template-JLCPCB_0.1.zip: ngff.kibot.yaml
	@$(KIBOT_CMD) -s all JLCPCB 2>> $(LOGFILE)

# Gerbers compatible with P-Ban
Fabrication/P-Ban/template-F_Cu_0.1.gtl Fabrication/P-Ban/template-B_Cu_0.1.gbl Fabrication/P-Ban/template-In1_Cu_0.1.gp1 Fabrication/P-Ban/template-In2_Cu_0.1.gp2 Fabrication/P-Ban/template-In3_Cu_0.1.gp3 Fabrication/P-Ban/template-In4_Cu_0.1.gp4 Fabrication/P-Ban/template-F_SilkS_0.1.gto Fabrication/P-Ban/template-B_SilkS_0.1.gbo Fabrication/P-Ban/template-F_Mask_0.1.gts Fabrication/P-Ban/template-B_Mask_0.1.gbs Fabrication/P-Ban/template-Edge_Cuts_0.1.gm1 Fabrication/P-Ban/製造基準書.txt: ngff.kicad_pcb ngff.kibot.yaml
	@$(KIBOT_CMD) -s all P-Ban_gerbers 2>> $(LOGFILE)

# Drill files compatible with P-Ban
Fabrication/P-Ban/ngff.drl Fabrication/P-Ban/template-drill_map_0.1.gbr Fabrication/P-Ban/template-drl.rpt: ngff.kicad_pcb ngff.kibot.yaml
	@$(KIBOT_CMD) -s all P-Ban_drill 2>> $(LOGFILE)

# ZIP file for P-Ban
Fabrication/P-Ban/template-P-Ban_0.1.zip: ngff.kibot.yaml
	@$(KIBOT_CMD) -s all P-Ban 2>> $(LOGFILE)

# Gerbers compatible with PCBWay
Fabrication/PCBWay/ngff.gtl Fabrication/PCBWay/ngff.gl2 Fabrication/PCBWay/ngff.gl3 Fabrication/PCBWay/ngff.gl4 Fabrication/PCBWay/ngff.gl5 Fabrication/PCBWay/ngff.gbl Fabrication/PCBWay/ngff.gto Fabrication/PCBWay/ngff.gbo Fabrication/PCBWay/ngff.gts Fabrication/PCBWay/ngff.gbs Fabrication/PCBWay/ngff.gtp Fabrication/PCBWay/ngff.gbp Fabrication/PCBWay/ngff.gm1: ngff.kicad_pcb ngff.kibot.yaml
	@$(KIBOT_CMD) -s all PCBWay_gerbers 2>> $(LOGFILE)

# Drill files compatible with PCBWay
Fabrication/PCBWay/ngff.drl Fabrication/PCBWay/template-NPTH.drl: ngff.kicad_pcb ngff.kibot.yaml
	@$(KIBOT_CMD) -s all PCBWay_drill 2>> $(LOGFILE)

# ZIP file for PCBWay
Fabrication/PCBWay/template-PCBWay_0.1.zip: ngff.kibot.yaml
	@$(KIBOT_CMD) -s all PCBWay 2>> $(LOGFILE)

# Print schematic (PDF)
Fabrication/template-schematic_0.1.pdf: Power.sch ngff.sch ngff.kibot.yaml
	@$(KIBOT_CMD) -s all print_sch 2>> $(LOGFILE)

# Print F.Cu+Dwgs.User
Fabrication/template-F_Cu+Dwgs_User_0.1.pdf: ngff.kicad_pcb ngff.kibot.yaml
	@$(KIBOT_CMD) -s all print_front 2>> $(LOGFILE)

# Print B.Cu+Dwgs.User
Fabrication/template-B_Cu+Dwgs_User_0.1.pdf: ngff.kicad_pcb ngff.kibot.yaml
	@$(KIBOT_CMD) -s all print_bottom 2>> $(LOGFILE)

# Print GND+Dwgs.User
Fabrication/template-GND+Dwgs_User_0.1.pdf: ngff.kicad_pcb ngff.kibot.yaml
	@$(KIBOT_CMD) -s all print_gnd 2>> $(LOGFILE)

# Print Power_+3,3V+Dwgs.User
Fabrication/template-Power_+3,3V+Dwgs_User_0.1.pdf: ngff.kicad_pcb ngff.kibot.yaml
	@$(KIBOT_CMD) -s all print_power 2>> $(LOGFILE)

# Print Señal_1+Dwgs.User
Fabrication/template-S1_Cu+Dwgs_User_0.1.pdf: ngff.kicad_pcb ngff.kibot.yaml
	@$(KIBOT_CMD) -s all print_s1 2>> $(LOGFILE)

# Print Señal_2+Dwgs.User
Fabrication/template-S2_Cu+Dwgs_User_0.1.pdf: ngff.kicad_pcb ngff.kibot.yaml
	@$(KIBOT_CMD) -s all print_s2 2>> $(LOGFILE)

# Interactive Bill of Materials (HTML)
Fabrication/BoM/template-ibom_0.1.html: ngff.kicad_pcb ngff.kibot.yaml
	@$(KIBOT_CMD) -s all interactive_bom 2>> $(LOGFILE)

# Bill of Materials in HTML format
Fabrication/BoM/template-bom_0.1.html: Power.sch ngff.sch ngff.kibot.yaml
	@$(KIBOT_CMD) -s all bom_html 2>> $(LOGFILE)

# Bill of Materials in XLSX format
Fabrication/BoM/template-bom_0.1.xlsx: Power.sch ngff.sch ngff.kibot.yaml
	@$(KIBOT_CMD) -s all bom_xlsx 2>> $(LOGFILE)

# Bill of Materials in CSV format
Fabrication/BoM/template-bom_0.1.csv: Power.sch ngff.sch ngff.kibot.yaml
	@$(KIBOT_CMD) -s all bom_csv 2>> $(LOGFILE)

# Gerbers for the board house
Fabrication/Gerbers/template-F_Cu_0.1.gbr Fabrication/Gerbers/template-B_Cu_0.1.gbr Fabrication/Gerbers/template-GND_Cu_0.1.gbr Fabrication/Gerbers/template-Power_Cu_0.1.gbr Fabrication/Gerbers/template-S1_Cu_0.1.gbr Fabrication/Gerbers/template-S2_Cu_0.1.gbr Fabrication/Gerbers/template-F_Paste_0.1.gbr Fabrication/Gerbers/template-B_Paste_0.1.gbr Fabrication/Gerbers/template-F_SilkS_0.1.gbr Fabrication/Gerbers/template-B_SilkS_0.1.gbr Fabrication/Gerbers/template-F_Mask_0.1.gbr Fabrication/Gerbers/template-B_Mask_0.1.gbr Fabrication/Gerbers/template-Dwgs_User_0.1.gbr Fabrication/Gerbers/template-Edge_Cuts_0.1.gbr Fabrication/Gerbers/template-B_Fab_0.1.gbr Fabrication/Gerbers/template-job.gbrjob: ngff.kicad_pcb ngff.kibot.yaml
	@$(KIBOT_CMD) -s all gerbers 2>> $(LOGFILE)

# Excellon drill files
Fabrication/Drill/template-PTH_drill_0.1.drl Fabrication/Drill/template-PTH_drill_map_0.1.pdf Fabrication/Drill/template-NPTH_drill_0.1.drl Fabrication/Drill/template-NPTH_drill_map_0.1.pdf Fabrication/Drill/template-drl.rpt: ngff.kicad_pcb ngff.kibot.yaml
	@$(KIBOT_CMD) -s all excellon_drill 2>> $(LOGFILE)

# Gerber drill files
Fabrication/Drill/template-PTH_drill_0.1.gbr Fabrication/Drill/template-NPTH_drill_0.1.gbr: ngff.kicad_pcb ngff.kibot.yaml
	@$(KIBOT_CMD) -s all gerber_drills 2>> $(LOGFILE)

# Pick and place file
Fabrication/Position/template-top_pos_0.1.pos Fabrication/Position/template-bottom_pos_0.1.pos: ngff.kicad_pcb ngff.kibot.yaml
	@$(KIBOT_CMD) -s all position 2>> $(LOGFILE)

# PCB render top green
Fabrication/PCB/green/template-top_0.1.jpg: ngff.kicad_pcb ngff.kibot.yaml
	@$(KIBOT_CMD) -s all pcb_top_g 2>> $(LOGFILE)

# PCB render bottom green
Fabrication/PCB/green/template-bottom_0.1.jpg: ngff.kicad_pcb ngff.kibot.yaml
	@$(KIBOT_CMD) -s all pcb_bot_g 2>> $(LOGFILE)

# PCB render top blue
Fabrication/PCB/blue/template-top_0.1.jpg: ngff.kicad_pcb ngff.kibot.yaml
	@$(KIBOT_CMD) -s all pcb_top_b 2>> $(LOGFILE)

# PCB render bottom blue
Fabrication/PCB/blue/template-bottom_0.1.jpg: ngff.kicad_pcb ngff.kibot.yaml
	@$(KIBOT_CMD) -s all pcb_bot_b 2>> $(LOGFILE)

# PCB render top red
Fabrication/PCB/red/template-top_0.1.jpg: ngff.kicad_pcb ngff.kibot.yaml
	@$(KIBOT_CMD) -s all pcb_top_r 2>> $(LOGFILE)

# PCB render bottom red
Fabrication/PCB/red/template-bottom_0.1.jpg: ngff.kicad_pcb ngff.kibot.yaml
	@$(KIBOT_CMD) -s all pcb_bot_r 2>> $(LOGFILE)

# Generate 3D model (STEP)
Fabrication/3D/template-3D_0.1.step: ngff.kicad_pcb ../src/modelos.3dshapes/B3U_3000PB.wrl ../src/modelos.3dshapes/MPU-9250.wrl ../src/modelos.3dshapes/usb_B_micro_smd.wrl ../src/modelos.3dshapes/MCP73821.wrl ../src/modelos.3dshapes/c_0201.wrl ../src/modelos.3dshapes/c_0402.wrl ../src/modelos.3dshapes/LBCA2HNZYZ-711.wrl ../src/modelos.3dshapes/MKL03Z32CAF4R_20-WLCSP_1.995x1.609.wrl ../src/modelos.3dshapes/sod323.wrl ../src/modelos.3dshapes/TPS2115A.wrl ../src/modelos.3dshapes/ABS05-32.768KHZ-9-T.wrl ../src/modelos.3dshapes/r_0402.wrl ../src/modelos.3dshapes/SML-LX0404SIUPGUSB.wrl ../src/modelos.3dshapes/df12(3.0)-10dp-0.5v.wrl ../src/modelos.3dshapes/r_0201.wrl ../src/modelos.3dshapes/TPS82740B.wrl ngff.kibot.yaml
	@$(KIBOT_CMD) -s all step 2>> $(LOGFILE)

.PHONY: all pre_sch out_sch all_sch pre_pcb out_pcb all_pcb run_erc run_drc Elecrow_gerbers Elecrow_drill Elecrow FusionPCB_gerbers FusionPCB_drill FusionPCB JLCPCB_gerbers JLCPCB_drill JLCPCB P-Ban_gerbers P-Ban_drill P-Ban PCBWay_gerbers PCBWay_drill PCBWay print_sch print_front print_bottom print_gnd print_power print_s1 print_s2 interactive_bom bom_html bom_xlsx bom_csv gerbers excellon_drill gerber_drills position pcb_top_g pcb_bot_g pcb_top_b pcb_bot_b pcb_top_r pcb_bot_r step
